import { GraduationCap, School, ShieldCheck } from "lucide-react";

export const roleConfig = {
	admin: {
		icon: ShieldCheck,
		label: "مدیر سیستم",
	},
	teacher: {
		icon: School,
		label: "استاد",
	},
	student: {
		icon: GraduationCap,
		label: "دانشجو",
	},
} as const;

export const defaultStyles = {
	wrapper: [
		"min-h-[400px]",
		"border",
		"border-neutral-200/10",
		"dark:border-neutral-800/10",
		"rounded-3xl",
		"shadow-2xl",
		"bg-white/60",
		"dark:bg-neutral-900/60",
		"backdrop-blur-xl",
		"backdrop-saturate-150",
		"overflow-hidden",
	].join(" "),
	th: [
		"bg-neutral-50/50",
		"dark:bg-neutral-800/50",
		"backdrop-blur-lg",
		"text-xs",
		"font-medium",
		"tracking-wide",
		"h-14",
		"text-right",
		"px-6",
		"first:rounded-tr-2xl",
		"last:rounded-tl-2xl",
		"border-b",
		"border-neutral-200/20",
		"dark:border-neutral-800/20",
	].join(" "),
	td: [
		"h-16",
		"text-right",
		"text-sm",
		"px-6",
		"border-b",
		"border-neutral-100/10",
		"dark:border-neutral-800/10",
	].join(" "),
	search: [
		"h-12",
		"bg-white/50",
		"dark:bg-neutral-900/50",
		"backdrop-blur-xl",
		"border-2",
		"border-neutral-200/50",
		"dark:border-neutral-800/50",
		"rounded-2xl",
		"px-4",
		"transition-all",
		"duration-300",
		"hover:border-primary-400/50",
		"focus:border-primary-500",
		"shadow-lg",
		"shadow-neutral-200/20",
		"dark:shadow-neutral-900/20",
	].join(" "),
	idBadge: [
		"inline-flex",
		"items-center",
		"gap-1",
		"px-3",
		"py-1.5",
		"bg-neutral-100/50",
		"dark:bg-neutral-800/50",
		"backdrop-blur-md",
		"backdrop-saturate-150",
		"border",
		"border-neutral-200/20",
		"dark:border-neutral-700/20",
		"rounded-full",
		"font-mono",
		"text-xs",
		"shadow-sm",
		"transition-transform",
		"duration-200",
		"hover:scale-105",
	].join(" "),
	badgeStyles: {
		admin: {
			base: [
				"inline-flex",
				"items-center",
				"justify-center",
				"gap-2",
				"min-w-[120px]",
				"px-4",
				"py-2",
				"rounded-2xl",
				"bg-gradient-to-r",
				"from-emerald-400/10",
				"to-emerald-500/10",
				"dark:from-emerald-400/5",
				"dark:to-emerald-500/5",
				"backdrop-blur-xl",
				"backdrop-saturate-150",
				"border",
				"border-emerald-400/20",
				"dark:border-emerald-400/10",
				"shadow-lg",
				"shadow-emerald-500/10",
				"transition-all",
				"duration-300",
				"hover:scale-105",
				"hover:shadow-emerald-500/20",
				"group",
			].join(" "),
			icon: "w-4 h-4 text-emerald-500 transition-transform duration-300 group-hover:scale-110",
			content:
				"text-emerald-700 dark:text-emerald-300 font-medium tracking-wide",
		},
		teacher: {
			base: [
				"inline-flex",
				"items-center",
				"justify-center",
				"gap-2",
				"min-w-[120px]",
				"px-4",
				"py-2",
				"rounded-2xl",
				"bg-gradient-to-r",
				"from-blue-400/10",
				"to-blue-500/10",
				"dark:from-blue-400/5",
				"dark:to-blue-500/5",
				"backdrop-blur-xl",
				"backdrop-saturate-150",
				"border",
				"border-blue-400/20",
				"dark:border-blue-400/10",
				"shadow-lg",
				"shadow-blue-500/10",
				"transition-all",
				"duration-300",
				"hover:scale-105",
				"hover:shadow-blue-500/20",
				"group",
			].join(" "),
			icon: "w-4 h-4 text-blue-500 transition-transform duration-300 group-hover:scale-110",
			content: "text-blue-700 dark:text-blue-300 font-medium tracking-wide",
		},
		student: {
			base: [
				"inline-flex",
				"items-center",
				"justify-center",
				"gap-2",
				"min-w-[120px]",
				"px-4",
				"py-2",
				"rounded-2xl",
				"bg-gradient-to-r",
				"from-amber-400/10",
				"to-amber-500/10",
				"dark:from-amber-400/5",
				"dark:to-amber-500/5",
				"backdrop-blur-xl",
				"backdrop-saturate-150",
				"border",
				"border-amber-400/20",
				"dark:border-amber-400/10",
				"shadow-lg",
				"shadow-amber-500/10",
				"transition-all",
				"duration-300",
				"hover:scale-105",
				"hover:shadow-amber-500/20",
				"group",
			].join(" "),
			icon: "w-4 h-4 text-amber-500 transition-transform duration-300 group-hover:scale-110",
			content: "text-amber-700 dark:text-amber-300 font-medium tracking-wide",
		},
	},
	buttonStyles: {
		primary: [
			"bg-gradient-to-r",
			"from-primary-500",
			"to-primary-600",
			"hover:from-primary-400",
			"hover:to-primary-500",
			"text-white",
			"shadow-lg",
			"shadow-primary-500/25",
			"hover:shadow-primary-500/35",
			"rounded-xl",
			"transition-all",
			"duration-200",
		].join(" "),
		secondary: [
			"bg-white",
			"dark:bg-neutral-800",
			"hover:bg-neutral-50",
			"dark:hover:bg-neutral-700",
			"border",
			"border-neutral-200",
			"dark:border-neutral-700",
			"text-neutral-700",
			"dark:text-neutral-300",
			"shadow-md",
			"hover:shadow-lg",
			"dark:shadow-neutral-900/30",
			"rounded-xl",
			"transition-all",
			"duration-200",
		].join(" "),
		danger: [
			"bg-white",
			"dark:bg-neutral-800",
			"hover:bg-red-50",
			"dark:hover:bg-red-900/20",
			"text-red-600",
			"dark:text-red-400",
			"hover:text-red-700",
			"dark:hover:text-red-300",
			"border",
			"border-red-200",
			"dark:border-red-700/50",
			"shadow-md",
			"hover:shadow-lg",
			"dark:shadow-neutral-900/30",
			"rounded-xl",
			"transition-all",
			"duration-200",
		].join(" "),
	},
};
